#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PHASE="$ROOT/scripts/phase-public-network-verify.sh"

[[ -x "$PHASE" ]]
grep -Fq 'GDC_CHAIN_PUBLIC_BASE must be an HTTPS public participant endpoint' "$PHASE"
grep -Fq 'chain-api/productscience/inference/inference/participant' "$PHASE"
grep -Fq 'chain-rpc/validators?per_page=100' "$PHASE"
grep -Fq 'capture_canonical_genesis' "$PHASE"
grep -Fq 'hardware_nodes/$address' "$PHASE"
grep -Fq 'qwen3-0.6b:$address' "$PHASE"
grep -Fq 'GDC_VERIFY_EXPECTED_ACTIVE_COUNT' "$PHASE"
grep -Fq 'GDC_EXPECTED_TOPOLOGY_FILE' "$PHASE"
grep -Fq 'expected current-run topology' "$PHASE"
grep -Fq 'GDC_EXTERNAL_JOIN_RECEIPT_DIR' "$PHASE"
grep -Fq 'operator_mode == "external-operator"' "$PHASE"
grep -Fq 'GDC_GATE_A_EVIDENCE_DIR' "$PHASE"
grep -Fq 'expected_active_count == 2' "$PHASE"
grep -Fq 'GDC_CPOC_PROBE_EPOCHS' "$PHASE"
grep -Fq 'expected_active_count:$expected_active_count' "$PHASE"
grep -Fq 'active_participant_count:$active_participant_count' "$PHASE"
grep -Fq 'effective_validator_count:$effective_validator_count' "$PHASE"
grep -Fq 'check-validation-weight-evidence.sh' "$PHASE"
grep -Fq 'record_poc_snapshot' "$PHASE"
grep -Fq 'poc_coverage_complete' "$PHASE"
grep -Fq 'poc_coverage=$poc_coverage' "$PHASE"
grep -Fq 'or .status == 1' "$PHASE"
grep -Fq '# Public network verification: $verdict' "$PHASE"
grep -Fq 'write_verdict BLOCKED' "$PHASE"
grep -Fq 'write_verdict INCONCLUSIVE' "$PHASE"
grep -Fq 'active_confirmation_poc_event' "$PHASE"
grep -Fq 'confirmation_poc_events/$observed_epoch' "$PHASE"
grep -Fq 'CONFIRMATION_POC_GRACE_PERIOD' "$PHASE"
grep -Fq 'CONFIRMATION_POC_GENERATION' "$PHASE"
grep -Fq 'CONFIRMATION_POC_VALIDATION' "$PHASE"
grep -Fq 'CONFIRMATION_POC_COMPLETED' "$PHASE"
grep -Fq 'confirmation-PoC deadline epoch' "$PHASE"
! grep -Fq 'node_account_file' "$PHASE"
! grep -Fq 'node_identity_file' "$PHASE"
! grep -Fq 'ssh "$GENESIS_NODE"' "$PHASE"

echo 'PASS public network observer contract'
